### ISSUE TITLE
How to compute or get fisher_exp.npy

### ISSUE THREAD

**Issue by ar-rehman135** [holyseven/TransferLearningClassification#2]
Hello,

I want to reproduce the results of the research paper. But I am having issue computing fisher information matrix for L2-SP Fisher technique. Can you please guide.

**Comment by holyseven** [comment]
Hi,

here are the files, which are computed by the formula `\hat{F_{jj}}` in the [paper](https://arxiv.org/pdf/1802.01483.pdf). 

fisher_imagenet_resnet101: https://drive.google.com/open?id=1QRY61IPC9aQbkX0aaC29pq7h2tXfnimp

fisher_places_resnet152: https://drive.google.com/open?id=1Y81D5z16g2MXK7XCN4dFkrB2T1Chl1kb
